version: '3.5'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 7001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on: 
      - mongo
  app:
    build: ./backend
    environment:
      NODE_ENV: dev
      CHAIN_START_ERA: 21 # the era at which chain starts rewarding the delegators
      CHAIN_START_BLOCK: 1 # the block at which chain starts parsing
      STAKE_DROP: "start" # if other value or undefined, stake drop will be paused
      ONLY_WHITE_LISTED_VALIDATORS: "true" #if false, all validators will be considered
      ONLY_REGISTERED_ADDRESSES: "true" #if false, all delegators will be rewarded
      POLKADOT_RPC: "http://34.93.40.96:4443/"
      PRE_SHARED_KEY: "abcd1234"
      DISTRIBUTION_CONTRACT_ADDRESS: "0x7b45587B7a993aE4481A713de4a4b487C05308C2"
      STAKE_REGISTRY_CONTRACT_ADDRESS: "0x04149a2cCb98f649302BbdCc4a3D7118B7ABcAf5"
      TOKEN_CONTRACT_ADDRESS: "0x9c2B9044e1e52f2fAC04A4A843C2d4cE9f5Ff3f0"
      FEED_URL: "http://172.17.0.1:3000/polkadot"
      VALIDATE_TRANSACTION_HASH: "false"
    volumes:
      - ./backend:/home/app
    ports:
      - 3001:3000
    depends_on: 
      - mongo
      - mongo-express


# // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# // Distribution address 0x7b45587B7a993aE4481A713de4a4b487C05308C2
# // ValidatorRegistry address 0x56dF8F7306DceECf9Bb91b2ee861032D575E0972
# // StakeRegistry address 0x04149a2cCb98f649302BbdCc4a3D7118B7ABcAf5
# // AddressRegistry address 0x63B222F4222ac71DE4be09A06cE5C4Fd0B5a2635
# // mPondLogic address 0x49F86fAff3cf45C66872b1C1135f309Cd6468DB9
# // mPondProxy address 0x9c2B9044e1e52f2fAC04A4A843C2d4cE9f5Ff3f0
# // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%