version: '3.5'
services:
  app:
    build: ./backend
    environment:
      NODE_ENV: prod
      CHAIN_START_ERA: 196 # the era at which chain starts rewarding the delegators
      CHAIN_START_BLOCK: 2904165 # the block at which chain starts parsing
      STAKE_DROP: "start" # if other value or undefined, stake drop will be paused
      ONLY_WHITE_LISTED_VALIDATORS: "true" #if false, all validators will be considered
      ONLY_REGISTERED_ADDRESSES: "true" #if false, all delegators will be rewarded
      POLKADOT_RPC: "http://34.93.40.96:4443/" # change it in prod if needed
      NETWORK: "MATIC"
      FEED_URL: "http://172.17.0.1:3000/polkadot" # change this in prod
      VALIDATE_TRANSACTION_HASH: "true"
      MONGO_CONNECTION: "mongodb://admin:password@172.17.0.1:27017/admin" #change this in prod
    ports:
      - 3001:3000