version: '3.5'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 7001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on: 
      - mongo
  app:
    build: ./backend
    environment:
      NODE_ENV: dev
      CHAIN_START_ERA: 1 # the era at which chain starts rewarding the delegators
      CHAIN_START_BLOCK: 1 # the block at which chain starts parsing
      STAKE_DROP: "start" # if other value or undefined, stake drop will be paused
      ONLY_WHITE_LISTED_VALIDATORS: "true" #if false, all validators will be considered
      ONLY_REGISTERED_ADDRESSES: "true" #if false, all delegators will be rewarded
      POLKADOT_RPC: "http://34.93.40.96:4443/"
      PRE_SHARED_KEY: "abcd1234"
      DISTRIBUTION_CONTRACT_ADDRESS: "0xB46a01e8D723796686daea50619a61fcb4cB5ebA"
      STAKE_REGISTRY_CONTRACT_ADDRESS: "0x59F36dec32121B73150d65E11FE3D1c02B18A762"
      FEED_URL: "http://172.17.0.1:3000/polkadot"
      VALIDATE_TRANSACTION_HASH: "false"
    volumes:
      - ./backend:/home/app
    ports:
      - 3001:3000
    depends_on: 
      - mongo
      - mongo-express